# Site
name: 'GothCactus Mindscape'
description: 'Personal blog of gothcactus'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.png'
baseurl: '/blog'
disqus: 'gothcactus'
email: 'gothcactusblog@gmail.com'
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  
authors:
    gc:
      name:           gothcactus
      site:           https://gothcactus.com/blog
      avatar:         /assets/images/avatar1.png
      bio:            "the cluster of neurons behind these ramblings"
      email:          gothcactusblog@gmail.com
      twitter:        https://twitter.com/
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: gc
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]